[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_utils"
author = "Juan Buero"
author-email = "juan.buero@student.ie.edu"
description-file = "README.md"
requires = [
    "pandas",
    # "flask"
]

